name: Testing Workflow Variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud
  Greeting: hello

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Vishal"
        run: echo "${{ env.Greeting }} ${{ env.First_Name }} is using ${{ env.cloud }}"
        env:
          First_Name: Vishal
