name: Testing Workflow Variables

on:
  workflow_dispatch:

env:
  cloud: google-cloud
  Greeting: hello

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Mudassar"
        run: echo "$Greeting $First_Name is using $cloud"
        env:
          First_Name: Vishal
          Greeting: Hello
